services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppwd
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  api:
    build: .
    command: ["python", "-m", "uvicorn", "app.main:create_app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    env_file: .env
    volumes:
      - ./:/code
    working_dir: /code
    ports: ["8000:8000"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build: .
    command: ["celery", "-A", "app.workers.celery_app:celery", "worker", "-l", "INFO"]
    env_file: .env
    volumes:
      - ./:/code
    working_dir: /code
    depends_on:
      api:
        condition: service_started
      redis:
        condition: service_started

  beat:
    build: .
    command: ["celery", "-A", "app.workers.celery_app:celery", "beat", "-l", "INFO"]
    env_file: .env
    volumes:
      - ./:/code
    working_dir: /code
    depends_on:
      worker:
        condition: service_started
